        image:  
          db:
             repository: devopseasylearning2021/s4-db
             tag: "v1.4.2"
          ui:
             repository: devopseasylearning2021/s4-ui
             tag: "v1.5.6"
          auth:
             repository: devopseasylearning2021/s4-auth
             tag: "v3.4.1"
          weather:
             repository: devopseasylearning2021/s4-weather
             tag: "v2.5.4"
